package api

// Generated by https://quicktype.io

type Pokemon struct {
	Abilities              []Ability     `json:"abilities"`
	BaseExperience         int64         `json:"base_experience"`
	Forms                  []Species     `json:"forms"`
	GameIndices            []GameIndex   `json:"game_indices"`
	Height                 int64         `json:"height"`
	HeldItems              []HeldItem    `json:"held_items"`
	ID                     int64         `json:"id"`
	IsDefault              bool          `json:"is_default"`
	LocationAreaEncounters string        `json:"location_area_encounters"`
	Moves                  []Move        `json:"moves"`
	Name                   string        `json:"name"`
	Order                  int64         `json:"order"`
	PastTypes              []interface{} `json:"past_types"`
	Species                Species       `json:"species"`
	Sprites                Sprites       `json:"sprites"`
	Stats                  []Stat        `json:"stats"`
	Types                  []Type        `json:"types"`
	Weight                 int64         `json:"weight"`
}

type Ability struct {
	Ability  Species `json:"ability"`
	IsHidden bool    `json:"is_hidden"`
	Slot     int64   `json:"slot"`
}

type Species struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

type GameIndex struct {
	GameIndex int64   `json:"game_index"`
	Version   Species `json:"version"`
}

type HeldItem struct {
	Item           Species         `json:"item"`
	VersionDetails []VersionDetail `json:"version_details"`
}

type VersionDetail struct {
	Rarity  int64   `json:"rarity"`
	Version Species `json:"version"`
}

type Move struct {
	Move                Species              `json:"move"`
	VersionGroupDetails []VersionGroupDetail `json:"version_group_details"`
}

type VersionGroupDetail struct {
	LevelLearnedAt  int64   `json:"level_learned_at"`
	MoveLearnMethod Species `json:"move_learn_method"`
	VersionGroup    Species `json:"version_group"`
}

type GenerationV struct {
	BlackWhite Sprites `json:"black-white"`
}

type GenerationIv struct {
	DiamondPearl        Sprites `json:"diamond-pearl"`
	HeartgoldSoulsilver Sprites `json:"heartgold-soulsilver"`
	Platinum            Sprites `json:"platinum"`
}

type Versions struct {
	GenerationI    GenerationI             `json:"generation-i"`
	GenerationIi   GenerationIi            `json:"generation-ii"`
	GenerationIii  GenerationIii           `json:"generation-iii"`
	GenerationIv   GenerationIv            `json:"generation-iv"`
	GenerationV    GenerationV             `json:"generation-v"`
	GenerationVi   map[string]GenerationVi `json:"generation-vi"`
	GenerationVii  GenerationVii           `json:"generation-vii"`
	GenerationViii GenerationViii          `json:"generation-viii"`
}

type Sprites struct {
	BackDefault      string      `json:"back_default"`
	BackFemale       interface{} `json:"back_female"`
	BackShiny        string      `json:"back_shiny"`
	BackShinyFemale  interface{} `json:"back_shiny_female"`
	FrontDefault     string      `json:"front_default"`
	FrontFemale      interface{} `json:"front_female"`
	FrontShiny       string      `json:"front_shiny"`
	FrontShinyFemale interface{} `json:"front_shiny_female"`
	Other            *Other      `json:"other,omitempty"`
	Versions         *Versions   `json:"versions,omitempty"`
	Animated         *Sprites    `json:"animated,omitempty"`
}

type GenerationI struct {
	RedBlue RedBlue `json:"red-blue"`
	Yellow  RedBlue `json:"yellow"`
}

type RedBlue struct {
	BackDefault  string `json:"back_default"`
	BackGray     string `json:"back_gray"`
	FrontDefault string `json:"front_default"`
	FrontGray    string `json:"front_gray"`
}

type GenerationIi struct {
	Crystal Crystal `json:"crystal"`
	Gold    Crystal `json:"gold"`
	Silver  Crystal `json:"silver"`
}

type Crystal struct {
	BackDefault  string `json:"back_default"`
	BackShiny    string `json:"back_shiny"`
	FrontDefault string `json:"front_default"`
	FrontShiny   string `json:"front_shiny"`
}

type GenerationIii struct {
	Emerald          Emerald `json:"emerald"`
	FireredLeafgreen Crystal `json:"firered-leafgreen"`
	RubySapphire     Crystal `json:"ruby-sapphire"`
}

type Emerald struct {
	FrontDefault string `json:"front_default"`
	FrontShiny   string `json:"front_shiny"`
}

type GenerationVi struct {
	FrontDefault     string      `json:"front_default"`
	FrontFemale      interface{} `json:"front_female"`
	FrontShiny       string      `json:"front_shiny"`
	FrontShinyFemale interface{} `json:"front_shiny_female"`
}

type GenerationVii struct {
	Icons             DreamWorld   `json:"icons"`
	UltraSunUltraMoon GenerationVi `json:"ultra-sun-ultra-moon"`
}

type DreamWorld struct {
	FrontDefault string      `json:"front_default"`
	FrontFemale  interface{} `json:"front_female"`
}

type GenerationViii struct {
	Icons DreamWorld `json:"icons"`
}

type Other struct {
	DreamWorld      DreamWorld      `json:"dream_world"`
	OfficialArtwork OfficialArtwork `json:"official-artwork"`
}

type OfficialArtwork struct {
	FrontDefault string `json:"front_default"`
}

type Stat struct {
	BaseStat int64   `json:"base_stat"`
	Effort   int64   `json:"effort"`
	Stat     Species `json:"stat"`
}

type Type struct {
	Slot int64   `json:"slot"`
	Type Species `json:"type"`
}

// Generated by https://quicktype.io

type PokemonList struct {
	Count    int64       `json:"count"`
	Next     string      `json:"next"`
	Previous interface{} `json:"previous"`
	Results  []Result    `json:"results"`
}

type Result struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

// Generated by https://quicktype.io

type Encounter struct {
	LocationArea   LocationArea             `json:"location_area"`
	VersionDetails []EncounterVersionDetail `json:"version_details"`
}

type LocationArea struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

type EncounterVersionDetail struct {
	EncounterDetails []EncounterDetail `json:"encounter_details"`
	MaxChance        int64             `json:"max_chance"`
	Version          LocationArea      `json:"version"`
}

type EncounterDetail struct {
	Chance          int64          `json:"chance"`
	ConditionValues []LocationArea `json:"condition_values"`
	MaxLevel        int64          `json:"max_level"`
	Method          LocationArea   `json:"method"`
	MinLevel        int64          `json:"min_level"`
}
